# Generated by Django 4.0.6 on 2022-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
