# Generated by Django 4.0.6 on 2022-08-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_daily_item_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='name',
        ),
        migrations.AddField(
            model_name='daily',
            name='complete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='due_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='stay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Item_Stay',
        ),
    ]
