# Generated by Django 4.0.6 on 2022-10-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_daily_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
